### ISSUE TITLE
Consider a more normalized data shape

### ISSUE THREAD

**Issue by gaearon** [coodoo/react-redux-isomorphic-example#10]
I was looking at `products`, and its data shape is `{ all: [array of products], currentProduct: product }`. Wouldn't it be better to normalize it to `{ productsById: { id -> product }, fetchedProductIds: [array of ids], currentProductId: id }`? This would avoid duplicate state, and thus make features like editing, deleting, pagination easier. You can use https://github.com/gaearon/normalizr to help with this.

**Comment by coodoo** [comment]
Yep that's exactly what I planned to do next, along with introducing `immutablejs` to the example.

**Comment by coodoo** [comment]
Migrated the example to use `immutablejs".
