### ISSUE TITLE
Module not found: Error: Cannot resolve module 'react-router/lib/BrowserHistory'

### ISSUE THREAD

**Issue by LarryEitel** [coodoo/react-redux-isomorphic-example#14]
I am running latest Node on Windows. 

I ran: `npm run build`

```
ERROR in ./js/boot-client.js
Module not found: Error: Cannot resolve module 'react-router/lib/BrowserHistory' in F:\_vms\HomesteadCode\_live\misc\react-redux-isomorphic-example\js
 @ ./js/boot-client.js 49:36-78
```

**Comment by tarrencev** [comment]
package.json specifies "react-router": "^1.0.0-beta3" and beta4 is the latest release. beta4 breaks some behavior that is causing this.

Change the dependency requirement to "react-router": "1.0.0-beta3"

**Comment by coodoo** [comment]
Good call, just updated `package.json`, should be fine now.

As a side note, I won't upgrade `react-router` again until v1.0 is officially released.
