### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by kennetpostigo** [coodoo/react-redux-isomorphic-example#17]
Hey,

Great repo here! I would just like to suggest possibly adding `redux-simple-router` & updating dependencies. Besides that great job!

**Comment by coodoo** [comment]
This was long on my todo list, just had a quick jab on it with the new [`4.0` version](https://github.com/reactjs/react-router-redux/releases/tag/v4.0.0), and unfortunately to find the lib had become too complex and didn't quite work out of the box.

I don't have immediate need for it hence won't implement it but `PR` is always welcome!
