### ISSUE TITLE
English comments

### ISSUE THREAD

**Issue by vtambourine** [coodoo/react-redux-isomorphic-example#18]
Hey! I really liked your example and borrowed some stuff from it to my project. However, sometimes it's challenging to scan through code without being able to read all comments. Probably, it worth to have them in english?

**Comment by coodoo** [comment]
Just rewrite most comments from Chinese to English, let me know if there's any part that you find hard to comprehend, thanks.

**Comment by vtambourine** [comment]
Great, thank you!
