### ISSUE TITLE
How does optimistic updating work?

### ISSUE THREAD

**Issue by myndzi** [coodoo/react-redux-isomorphic-example#19]
I really like what you've got here, seems to strike a nice balance of simplicity and features. I was particularly interested in how you handle optimistic updating, but I can't quite work out how it is handled. In the promise middleware here:

https://github.com/coodoo/react-redux-isomorphic-example/blob/master/common/middlewares/PromiseMiddleware.js#L20-L28

It seems that you send the state object pre-request and post-request, regardless of if there is an error or anything like that. I guess the reducers handle what to do if there's an error? Then, in the reducers it seems that ADD_TO_CART_REQUEST, for example, just returns the current state, without doing any optimistic updates at all. Equally, none of the error reducers seem to do anything either. How's this supposed to work? Thanks!

**Comment by coodoo** [comment]
Good question, just added a quick example on how optimistic update could be implemented, have a look at [action](https://github.com/coodoo/react-redux-isomorphic-example/blob/master/common/actions/ShopActions.js#L29) and [reducer](https://github.com/coodoo/react-redux-isomorphic-example/blob/master/common/reducers/CartReducer.js#L11).

Basic trick is to add a transaction id `tid` in action so new object could be tracked, once server returned the persisted object we can update local object's `id` with the real one.

Let me know if you have further questions.

**Comment by myndzi** [comment]
Thank you :)
