### ISSUE TITLE
Question around initial state choice

### ISSUE THREAD

**Issue by dariocravero** [coodoo/react-redux-isomorphic-example#2]
Hi, I was wondering why did you choose to [store the state as a data attribute](https://github.com/coodoo/react-redux-isomorphic-example/blob/master/assets/index.html#L11) and [parse it afterwards](https://github.com/coodoo/react-redux-isomorphic-example/blob/master/js/boot.js#L19-L23) instead of putting it as a script that gets resolved (and parsed) by the browser? Did you find any benefits to that approach (other than having no global variable?)? Cheers, Darío :)

**Comment by coodoo** [comment]
Not really, it was simply carried over from my previous [alt example](https://github.com/coodoo/react-alt-isomorphic-example), and I just revised that to be a scripts, thanks for bringing that to attention :)

**Comment by dariocravero** [comment]
Good stuff :)
