### ISSUE TITLE
componentWillMount usage

### ISSUE THREAD

**Issue by dpwrussell** [coodoo/react-redux-isomorphic-example#20]
Hi,

I am trying to understand your usage of `componentWillMount` rather than `componentDidMount`. Your isomorphic example is the only one I have found where `componentWillMount` is actually being used. As the documentation specifies, `componentWillMount` will run on both server and client side. Thus when I found it in your code, it made a sort of sense to me, but I don't think it actually achieves anything (it might actually just be slowing things down) because the data fetching occurs when you run `fetchComponentData` on the components. This is the part that uses promises in order to guarantee that everything has finished loading before the page is rendered server side.

Per component async fetching I think still remains unimplemented (https://github.com/facebook/react/issues/1739) so I think probably you just meant to use `componentDidMount` instead?

Example: https://github.com/coodoo/react-redux-isomorphic-example/blob/master/common/components/ProductsContainer.jsx#L26

Finally, awesome work on this example. There are precious few up-to-date react isomorphic examples out there and yours is saving me a lot of time!

Cheers

**Comment by coodoo** [comment]
Good catch, I did mean to use `componentDidMount`, just updated the example, thanks for the reminder!
