### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by felixsanz** [coodoo/react-redux-isomorphic-example#21]
├─┬ UNMET PEER DEPENDENCY react@15.0.0-rc.2
│ └─┬ fbjs@0.8.0-alpha.3 
│   └─┬ isomorphic-fetch@2.2.1 
│     ├─┬ node-fetch@1.3.3 
│     │ └─┬ encoding@0.1.12 
│     │   └── iconv-lite@0.4.13 
│     └── whatwg-fetch@0.11.0 
└── react-dom@15.0.0-rc.2 

npm WARN redbox-react@1.2.2 requires a peer of react@>=0.13.2 || ^0.14.0-rc1 but none was installed.
npm WARN redux-devtools@3.1.1 requires a peer of react@^0.14.0 but none was installed.

**Comment by coodoo** [comment]
Yep I saw those warnings too but seemed it does no harm so probably just ignore it?
