### ISSUE TITLE
DevTools problem

### ISSUE THREAD

**Issue by davscro** [coodoo/react-redux-isomorphic-example#22]
When you enable devtools you end up with error:

`Error: Cannot find module 'redux-devtools/lib/react'`

**Comment by coodoo** [comment]
Yep `devtools` is currently disabled, will put it back in next commit.

**Comment by coodoo** [comment]
Fixed and committed, you can [toggle the devtools here](https://github.com/coodoo/react-redux-isomorphic-example/blob/master/common/utils/configureStore.js#L8), let me know if you have further questions.

**Comment by davscro** [comment]
Thank you. Regards
