### ISSUE TITLE
How to have isomorphic data fetching? 

### ISSUE THREAD

**Issue by mocheng** [coodoo/react-redux-isomorphic-example#24]
For the time being, the RESTful API is simulated by setTimeout. In true life, how to have browser and server side have same code to fetch data?

**Comment by coodoo** [comment]
See following pseudo code from [getAllProducts](https://github.com/coodoo/react-redux-isomorphic-example/blob/master/common/utils/WebAPIUtils.js#L9) in `/common/utils/WebAPIUtils.js`.

``` javascript
// pseudo code
getAllProducts: function() {

    // invoke /products endpoint on server
    // which in turn shall invoke shopdb.getProducts() on server to fetch data then return to the client
    // note: this is just a fake endpoint for demo purpose, you need to implement it in nodejs
    fetch('http://localhost:3000/products')

    .then( res => res.json() )

    .then( data => {
        consolelog('fetched data', data)
        return convertToRecordMap( JSON.parse(data), ProductRecord )
    });
},
```

As a side note, you will also need to install [`isomorphic-fetch`](https://github.com/matthew-andrews/isomorphic-fetch) which provides `fetch` capability on both nodejs and browsers.

**Comment by mocheng** [comment]
From browser side, it makes sense. However, for server side, the `fetch` will take one "round-trip" to hit the sever endpoint, right? Seems a little wasteful.

How about this?

```
 const isomorhicFetcher = registerDataSource(ajaxPath, fetchFn, [PENDING, DONE, FAIL]);

 const allFetchers = {};
 function registerFetcher(ajaxPath, requiredParams, fetchFn, types) {
  allFetchers[ajaxPath] = fetchFn;

  return () => {
    var promise;

    if (global.window) {
      promise = fetch(ajaxPath).then((response) => {
        if (response.status === 200) {
          return response.json()
        } else {
          var failPromise = Promise.reject(response.status);
          failPromise.types = types;
          return failPromise;
        }
      });
    } else {
      promise = fetchFn()
    }
    promise.types = types;

    return promise;
  }
```

**Comment by coodoo** [comment]
> From browser side, it makes sense. However, for server side, the fetch will take one "round-trip" to hit the sever endpoint, right? Seems a little wasteful.

Not a waste if you happen to have stand-alone API servers in the first place (which is exactly my use case), but what you suggested should work too.
