### ISSUE TITLE
Enable Redux- Dev Tools

### ISSUE THREAD

**Issue by saurshaz** [coodoo/react-redux-isomorphic-example#5]
That would bring in productivity gain for sure. Redux-devtools. I would like to do that and make a pull request.

**Comment by coodoo** [comment]
Very looking forward to it, go ahead!

**Comment by coodoo** [comment]
Ended up I went ahead and added in the feature, have fun :)

**Comment by saurshaz** [comment]
Oh great, I was stuck up in some consulting work, so was looking up doing that this weekend hours. WIll take a pull. Kudos, again for sharing this and doing this redux-ness. :-)
