### ISSUE TITLE
compose middleware will got strength result

### ISSUE THREAD

**Issue by roth1002** [coodoo/react-redux-isomorphic-example#6]
When I run npm start and open browser to access localhost with port 3000

After click any second times 「Add to cart」 

it would happened ..... two of same product add to cart or add another product to cart

I even try 

```
import thunk from 'redux-thunk';
import promise from 'redux-promise';
```

and

modify

```
let finalCreateStore = compose(
    applyMiddleware(promiseMiddleware),
    devTools(),
    persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/)),
    createStore
  );
```

to

```
let finalCreateStore = compose(
    applyMiddleware(thunk, promise),
    devTools(),
    persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/)),
    createStore
  );
```

but still the same

**Comment by coodoo** [comment]
Thanks for reporting the bug, ended up it's the `redux-devtools` causing issues, just pushed a commit to disable it, will try to fix it later.

**Comment by roth1002** [comment]
:+1:

**Comment by coodoo** [comment]
It's fixed in the latest commit.

**Comment by roth1002** [comment]
:+1: 

but in reducers/products.js 

[`reducers/products.js`](https://github.com/coodoo/react-redux-isomorphic-example/blob/master/js/reducers/products.js#L50) the syntax:

array.find not support in chrome now.  (basic support in feature XD)
[`see here`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)
