### ISSUE TITLE
Problems with run dev and hot-reload

### ISSUE THREAD

**Issue by amorino** [coodoo/react-redux-isomorphic-example#7]
I ran `npm run dev`, the webpack bundle is VALID, however I cannot get the example to run. I think route "assets" causing is causing problems with the publicPath route "/static/" defined in the webpack.config.

Cheers.

**Comment by coodoo** [comment]
Try `npm start` instead, `dev.js` is no longer needed and just got removed.

**Comment by amorino** [comment]
Still I can't get hot-reload to work. 

Thanks.
